### PR TITLE
Added the game successfully 

### PR DESCRIPTION
**Pull request by Soumyajit2825**
#21 done

### CODE REVIEW

**Comment by alphadynamic00** [comment]
add a screenshot of the game.

**Comment by Soumyajit2825** [comment]
Screenshot 2022-10-23 132506

**Comment by Soumyajit2825** [comment]
@alphadynamic00

**Review by alphadynamic00 — COMMENTED** [review]
You have done a great work But the other one already there is a very good and better than this .
So if you want to get this added instead of adding this and removing the tictactoe folder you can change your  folder name to Tic-Tac-Toe-js and keep that folder also and make a PR.
Thank You.

**Pull request closed without merging**
